### ISSUE TITLE
[FEAT] 심박수 기능 구현

### ISSUE THREAD

**Issue by Dorodong96** [DeveloperAcademy-POSTECH/MC3-Team11-TopicRun#7]
### 문제 상황
- 심박수 기능 구현하기

### 해결 방안
- HealthKit 공부
 
### TODO
- [x] HealtKit 공부
- [x] Watch App 사용 여부 결정 (실시간 심박수)
- [x] 심박수 보여줄 수 있도록 구현

[07/26 진행 상황]
- [x] StartPage에서는 가장 최근의 심박수를 보여주기
- [x] 지도 뷰에서 TopicRun을 누르면 심박수를 위한 Workout Session 트리거
- [x] Workout 진행 동안 애플워치에서 표시되는 심박수를 폰에 전달
- [x] (수락) Let's Develop 버튼 누르면 Workout Session 종료
- [x] (취소) 이동 중 Stop 버튼 누르면 Workout Session 종료
- [X] 뒤로가기 버튼 누르면 Workout Session 종료
- [X] 아이폰 앱 종료시 Workout Session 종료

**Comment by Dorodong96** [comment]
[07/19 진행 상황]
- 실시간(에 가까운) 심박수 데이터를 읽어 오려면 Watch App을 활용해야 할 것 같습니다
- Watch App을 활용할 경우, HealthKit의[ HKWorkoutSession](https://developer.apple.com/documentation/healthkit/hkworkoutsession)을 통해 심박수 sample을 만들어서 띄워주는 방식으로 구현할 수 있을 것 같습니다.

**Comment by Dorodong96** [comment]
[07/26 진행 상황]
- [ ] StartPage에서는 가장 최근의 심박수를 보여주기
- [ ] 지도 뷰에서 TopicRun을 누르면 심박수를 위한 Workout Session 트리거
- [ ] Workout 진행 동안 애플워치에서 표시되는 심박수를 폰에 전달
- [ ] (수락) Let's Develop 버튼 누르면 Workout Session 종료
- [ ] (취소) Stop 버튼 누르면 Workout Session 종료
- [ ] 뒤로가기 버튼 누르면 Workout Session 종료
- [ ] 아이폰 앱 종료시 Workout Session 종료
